import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const { message } = await request.json();

    if (!message) {
      return NextResponse.json({ message: 'No message provided' }, { status: 400 });
    }

    // Mock AI response logic
    const aiResponse = `This is a mocked AI response to your message: "${message}". In a real application, this would be generated by an AI model.`;

    return NextResponse.json({ reply: aiResponse });
  } catch (error) {
    return NextResponse.json({ message: 'Error processing chat message' }, { status: 500 });
  }
}
